### ISSUE TITLE
HOWTO: Getting the emulator running under OSX

### ISSUE THREAD

**Issue by mengstr** [Hack-a-Day/Belgrade_Badge_Demoscene#3]
I use homebrew to install extra packages, if you are using something else you'll have to figure out this yourself :)

I first installed the SDL2 stuffs:

**brew install SDL2**
**brew install SDL2_gfx**

I then modified two lines in the Makefile as show in the bolded parts below:

gcc -std=c99 -c HaD_Badge.c bh-badge-animate.c **-I/usr/local/include/ -Wno-shift-op-parentheses**;
gcc HaD_Badge.o bh-badge-animate.o -o HaD_Badge  -lSDL2 -lSDL2_gfx **-L/usr/local/lib/**;

After that I could just do a make to compile and run the emulator.

**Comment by szczys** [comment]
Thanks, that will be a big help to all running OSX! I've added a note about this to the readme.
